# Generated by Django 5.0.4 on 2024-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('refimage', models.FileField(upload_to='uploads/')),
                ('reflink', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=12)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
    ]
