# Generated by Django 5.0.4 on 2024-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
