# Generated by Django 5.0.2 on 2024-05-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='refimage',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='reflink',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
