# Generated by Django 5.0.2 on 2024-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baked_and_ready',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='popular',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
